### PR TITLE
test: update CMCD tests to allow them to be run individually 

### LINKED ISSUE #6331: CMCD test pollution
CMCD tests seem to depend on a full test run of that suite to pass.  I was running tests with the filter "HLS" while working on an issue, and I got these CMCD failures:

```
$ ./build/test.py --use-xvfb --browsers Chrome --no-build --uncompiled --no-babel --filter '(HLS|Hls|hls|VTT|Vtt|vtt)'

Chrome 122.0.0.0 (Linux x86_64) CmcdManager CmcdManager instance adheres to the spec applies core CMCD params to networking engine requests hls manifest requests FAILED
	Error: Expected 'cmcd://foo' to contain 'ot%3Dm'.
	    at <Jasmine>
	    at UserContext.<anonymous> (test/util/cmcd_manager_unit.js:398:26)
	Error: Expected 'cmcd://foo' to contain 'sf%3Dh'.
	    at <Jasmine>
	    at UserContext.<anonymous> (test/util/cmcd_manager_unit.js:399:26)
Chrome 122.0.0.0 (Linux x86_64) CmcdManager CmcdManager instance adheres to the spec applies core CMCD params to networking engine requests hls playlist requests FAILED
	Error: Expected 'cmcd://foo' to contain 'ot%3Dm'.
	    at <Jasmine>
	    at UserContext.<anonymous> (test/util/cmcd_manager_unit.js:408:26)
	Error: Expected 'cmcd://foo' to contain 'sf%3Dh'.
	    at <Jasmine>
	    at UserContext.<anonymous> (test/util/cmcd_manager_unit.js:409:26)
```

When running all of the CMCD tests, they pass:

```
$ ./build/test.py --use-xvfb --browsers Chrome --no-build --uncompiled --no-babel --filter 'Cmcd'
[INFO] Running test (1 / 1, 0 failed so far)...
Running tests on: Chrome
Chrome 122.0.0.0 (Linux x86_64): Executed 29 of 2630 (skipped 2601) SUCCESS (0.583 secs / 0.012 secs)
TOTAL: 29 SUCCESS
```

The CMCD tests should not depend on each other for successful operation.

It looks like the CmcdManager instance in `test/util/cmcd_manager_unit.js` needs to be recreated in beforeEach(), rather than in a test body or beforeAll().

@littlespex, can you please take a look?

### PR DESCRIPTION
**Pull request by littlespex**
Closes #6331

### CODE REVIEW

**Comment by joeyparrish** [comment]
Sorry I'm late to this one...  I'm having a hard time understanding the fix.  I'll poke at it locally.

**Comment by joeyparrish** [comment]
This seems to fix the specific filter I gave in the bug, but I don't think it really addresses the root of the problem.

The tests still fail if you run the CmcdManager tests in a random order.  For example:

```sh
./build/test.py --use-xvfb --browsers Chrome --filter 'CmcdManager' --random --seed=1710532370757
```

I think the fundamental problem is as I mentioned in #6331: The CmcdManager instance needs to be recreated in beforeEach(), rather than in a test body or beforeAll().  You want each test to start with a new instance, so you know the test is independent of other tests.

**Comment by joeyparrish** [comment]
The seed I mentioned in the last comment definitely fails, but you can leave off the `--seed=` argument to get a new random seed each time.  You can also combine `--filter CmcdManager --random` with something like `--runs 10` to check that you have no hidden dependencies.

**Comment by littlespex** [comment]
This idea behind that section of test is to mimic a real playback scenario where multiple calls a made to the same instance. This ensures a request to the manifest don't pollute requests to the segments, etc.

**Comment by littlespex** [comment]
Fixed

**Review by avelad — APPROVED** [review]

**Review by joeyparrish — APPROVED** [review]
Thanks!

**Pull request merged**
