### PR TITLE
feat: Abr improvement config

### PR DESCRIPTION
**Pull request by Iragne**
I would like to propose an improvement of the AbrConfiguration with this 2 new parameter (as optional) and a new version of the SimpleAbrManager using that parameter for the switch this.switch_(chosenVariant /* , clearbuffer, safe margin*/);

Also  providing information about the parameter and updated the demo app with the capabilities to modify it.
Corrected the unit test and added specific unit test for it

### CODE REVIEW

**Comment by Iragne** [comment]
I'm not sure to understand why this test failed. The drm test player and the other one. Could it be link to other issue?

**Comment by theodab** [comment]
Our integration tests sometimes flake. It probably doesn't have anything to do with your PR.

**Comment by Iragne** [comment]
@theodab thanks for your feedback. Let me know you you have any questions about the pr.

**Comment by Iragne** [comment]
@theodab any update on this pr ?

**Review by avelad — APPROVED** [review]

**Pull request merged**
