### PR TITLE
fix(MSS): Fix parsing of PIFF Sample Encryption Box

### LINKED ISSUE #5390: PlayReady protected MSS fails in nightly demo on Edge
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.7-main-35-g6c71b0ee6-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67

**What did you do?**
1. Goto the shaka-player-demo nightly-built version from here.
https://index-dot-shaka-player-demo.appspot.com
2. Create a custom content with the following info:
Main->Manifest URL: https://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest
DRM->Custom License Server URL: https://playready.directtaps.net/pr/svc/rightsmanager.asmx
Name: Smooth PlayReady Test
3. Click "PLAY".

Content source:
https://github.com/androidx/media/blob/release-1.1.0/demos/main/src/main/assets/media.exolist.json#L264-L270

**What did you expect to happen?**
The stream starts playing.

**What actually happened?**
Playback didn't start and the following error message showed up:
```
Error code 3016
```
(No relevant error logs in the console)

**Additional info**
My environment:
Browser: Edge, Version 114.0.1823.67 (Official build) (64-bit)
OS: Windows 11 Pro, 22H2

The unprotected version of the same content works fine:
https://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest

### PR DESCRIPTION
**Pull request by unext-wendong**
Closes #5390

### CODE REVIEW

**Comment by avelad** [comment]
Please, sign the CLA! Also add some test in https://github.com/shaka-project/shaka-player/blob/main/test/mss/mss_player_integration.js for PlayReady. Thanks!

**Comment by unext-wendong** [comment]
Will figure out how to add an integration test.

**Comment by avelad** [comment]
@unext-wendong please sign the CLA! Thanks!

**Comment by unext-wendong** [comment]
@avelad Thanks.

**Pull request closed without merging**
