### PR TITLE
test: Update failing Safari screenshot

### PR DESCRIPTION
**Pull request by joeyparrish**

### CODE REVIEW

**Review by avelad — APPROVED** [review]

**Comment by joeyparrish** [comment]
I just launched a short, one-off test run in the lab, only for the layout tests, and only on Safari.  This should confirm that a single version of this screenshot will work for both GitHub CI and our lab device.  (It should, but you never know.)

The exact screenshot was taken from the output of a failed CI run in GitHub Actions and reviewed manually.

**Comment by avelad** [comment]
It doesn’t work in the lab :(

**Comment by joeyparrish** [comment]
Nope!  The version from GitHub Actions conflicts with the version from our lab.  😭

**Comment by joeyparrish** [comment]
The device in the lab identifies itself as:

> Safari 17.5 (macOS 10.15.7)

The version in GitHub Actions identifies itself as:

> Safari 17.5 (macOS 10.15.7)

🕷️ 👉 ❗ 👈 🕷️

**Comment by joeyparrish** [comment]
I'll cancel this for now so the lab tests stay green, but we need a way to differentiate between them if we want to skip a test case in GitHub Actions.

**Pull request closed without merging**
