### PR TITLE
fix(DASH): Clone closedCaptions map in PeriodCombiner output stream

### LINKED ISSUE #7303: DASH multi period generateVideoKey_ is not stable with close caption
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

Main and 4.11.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
yes

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
FF

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

I have a multi period stream with Close caption (only 1 track for CC)

**What did you expect to happen?**
I was expecting the   if (streams.has(key)) { to find my stream all the time in my multi period stream

**What actually happened?**

but in fact when debugging i was able to see that the key was not found in streams
My output stream has no CC information. so it's null meaning the key is like that
[false,768,30,"avc","video/mp4",null,[],**null**,1400000] 

But the key in the stream is like that
[false,768,30,"avc","video/mp4",null,[],**[]**,1400000]

look like the outputStream is not with the same structure as the stream, outputStream can be null and stream can be empty array

look the clone stream is not doing it correctly compare to the origin stream

**Are you planning send a PR to fix it?**

I'm sorry i have no time now to work on it 
Sorry guys

### PR DESCRIPTION
**Pull request by tykus160**
Fixes #7303

### CODE REVIEW

**Comment by avelad** [comment]
@Iragne Does it fix your issue?

**Comment by jeanalexandre-iragne-deltatre** [comment]
Thanks happy to test it

**Comment by Iragne** [comment]
> @Iragne Does it fix your issue?

I'm on it

**Review by joeyparrish — APPROVED** [review]
Looks good to me, but we can wait for confirmation of the fix before merging.

**Comment by Iragne** [comment]
@joeyparrish i need 1h sorry guys

**Comment by Iragne** [comment]
@joeyparrish  all good on my side thanks a lot team

**Review by avelad — APPROVED** [review]

**Pull request merged**
