### PR TITLE
feat(webvtt): webvtt colors output

### LINKED ISSUE #4545: Color information is being removed by the vtt parser (since Shaka 3.1.0)
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No. It doesn't load the subtitle at all in your demo (because `language` is "" I think)

**What browser and OS are you using?**
Chromium and Firefox. Happens on all OSes

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Doesn't apply

**What are the manifest and license server URIs?**
Doesn't apply. See code below

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```json
{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {}
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
            }
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\""
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "durationBackoff": 1,
        "forceTransmuxTS": false,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "ignoreDevicePixelRatio": false
    },
    "preferredAudioLanguage": "",
    "preferredTextLanguage": "",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "useHeaders": false
    }
}
```

**What did you do?**
Load a manifest with colored subtitles and add a `cuechange` listener logging the active cue and its `getCueAsHTML()` result.

```js
document.addEventListener('DOMContentLoaded', async function() {
  const video = document.getElementById('video');
  const player = new shaka.Player(video);
  //window.shaka = shaka;
  //window.player = player;
  player.setTextTrackVisibility(true);
  await player.load('https://ps.vemup.ctl.cdn.ebsd.ericsson.net/players/sdktesting/assets/006ce401-a493-453e-84b7-9afd9b055ffc_E5D874b/materials/sTgUrR65mh_E5D874b/webvtt-colors.ism/.mpd');
  const [ track ] = video.textTracks;
  track.addEventListener('cuechange', () => {
    if (track.activeCues.length) {
      const [ cue ] = track.activeCues;
      const div = document.createElement('div');
      div.appendChild(cue.getCueAsHTML());
      console.log('CUE' { cue, html: div.innerHTML });      
    }
  });
});
```

Then play the video and watch the debug log. When the subtitle says the name of a color ex "cyan", "lime", "red", these should have matching classes. This is needed to implement custom subtitle cue display logic.

**What did you expect to happen?**
The cue at 0:16 for example should have this text: `<c.lime>lime</c>` (or `<c.lime>lime</c.lime>` which seems to be valid too and works with your xml parser) and the `getCueAsHTML()` value should be `<span class="lime">lime</span>`. This is how it works in dash.js, hls.js and how it worked in Shaka before d882d28 (3.1.0).

**What actually happened?**
The cue at 0:16 just has the text `lime` and the `getCueAsHTML()` value is also just `lime`.

In addition to that, all the cues are actually displayed as white, rather than their real colors, but this is already covered by #4479

### PR DESCRIPTION
**Pull request by friday**
Adds color support for SimpleTextDisplayer and WebVttGenerator (only one place to fix both now thanks to #4941).

It's limited to the [8 colors classes](https://w3c.github.io/webvtt/#default-text-color) supported by the WebVTT specification, and also works with their 3 or 6-digit hex variants (if the stream has TTML subtitles). 

It does not support rgb, rgba or any colors other than these 8.

Fixes #4545

### CODE REVIEW

**Comment by avelad** [comment]
@friday I'll add some minor changes to support more TTML colors (eg), and I'll also try to add some test with your permission.

**Comment by friday** [comment]
> @friday I'll add some minor changes to support more TTML colors (eg), and I'll also try to add some test with your permission.

Appreciated 👍

**Comment by avelad** [comment]
@friday I have already added the changes, in case you want to review.

**Comment by avelad** [comment]
@joeyparrish , I think the `web_vtt_layout_integration.js` tests should include some of these cases, what do you think?

**Review by avelad — APPROVED** [review]

**Review by friday — COMMENTED** [review]
Approved @avelad :+1: (and updated description)

This does mean that other colors like `orange`, `pink` etc would be removed, which may or may not be a good thing. I like the clarity of drawing the line at these 8 colors (and their hex variants) though.

About TTML color formats, I never used them myself, so I don't know what is more common, but [from what I read](https://www.w3.org/TR/2018/REC-ttml1-20181108/#style-value-color) I believe they can be named colors, 6 or 8 digit hex (for alpha channel), rgb or rgba. I wouldn't be surprised if 3 digit hex was also commonly supported and used though.

Supporting rgb(a) is harder to parse efficiently since they're not white-space sensitive, and it would add more complexity and regex.

**Pull request merged**
