### PR TITLE
fix: Fallback to isTypeSupported when cast namespace is undefined

### LINKED ISSUE #5010: VIZIO SmartCast TV is being incorrectly categorized as a Chromecast, breaking DRM playback
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
VIZIO TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
`Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 CrKey/1.0.999999 VIZIO SmartCast(Conjure/SX7A-4.6.419.12 FW/11.0.120.1-1 Model/M65-D0)`

**What are the manifest and license server URIs?**

Available upon request

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Configure a player to play DRM protected content on a VIZIO SmartCast TV.

**What did you expect to happen?**
Video should play.

**What actually happened?**

Player throws an 8000 error. 

219510466-7ff35810-08de-4f4b-8b4c-f826f1f075c6

### PR DESCRIPTION
**Pull request by littlespex**
Resolves #5010

### CODE REVIEW

**Comment by avelad** [comment]
@littlespex is it ready for review?

**Comment by littlespex** [comment]
I'm waiting on verification on a few other devices. I will pull it out of draft later today.

**Comment by littlespex** [comment]
@avelad Verification is complete and the PR is ready for review.

**Review by avelad — APPROVED** [review]

**Comment by avelad** [comment]
@JulianDomingo, can you review it?, if I remember correctly you implemented this part.

**Comment by joeyparrish** [comment]
LGTM, but I would like Julian to confirm.  I'll do a test run in the lab to be certain it doesn't break existing test cases.

**Review by JulianDomingo — APPROVED** [review]
No objections, thanks for pointing out and correcting the Vizio use case.

**Pull request merged**
