### PR TITLE
fix: Exclude TIMEOUT errors when disabling streams

### LINKED ISSUE #7368: Stuck in a loop when VOD segments timeout
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.9.2-caf1 through 4.9.28 and main

**Can you reproduce the issue with our latest release version?**
Did not try

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app (partner Cast app)

**If custom app, can you reproduce the issue using our demo app?**
Did not try

**What browser and OS are you using?**
Chromecast Gen 3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Cast 1.52.something (a bit behind)

**What are the manifest and license server URIs?**

Shared privately by partner (b/368055424 internally)

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Default on CAF

**What did you do?**

Load with poor network throughput.  You can limit throughput to 20kB/s in the debugger to see this quickly.

**What did you expect to happen?**
Playback should eventually fail with a timeout.

**What actually happened?**

StreamingEngine disables a stream (audio or video, whichever times out first), then the player chooses a new variant.  30s later, the first stream is re-enabled, then the new one times out, etc.  Forever in a loop, with no fatal error.

**Are you planning send a PR to fix it?**
Yes

**Misc**
This was introduced in https://github.com/shaka-project/shaka-player/pull/5057 and v4.4.0, which moved the logic and dropped a condition (maybe on accident?).  Prior to this, the disable logic only fired on `code == HTTP_ERROR`.  Now it fires on all `category == NETWORK` errors.

One solution is to add that condition back.

Another is to only disable streams in live content.  I think it doesn't make sense to do it in VOD, since VOD is static and doesn't "recover".

### PR DESCRIPTION
**Pull request by joeyparrish**
In #7368, we get stuck in a loop loading forever.  This regression was introduced in v4.4.0 and affects all v4.4, v4.5, v4.6, v4.7, and v4.8 releases, as well as v4.9.0-28, v4.9.2-caf1, v4.10.0-20, and v4.11.0-6.

The loop is composed of these elements:

1. an error that triggers disabling a stream
2. an error that doesn't resolve itself over time
3. an error that is slow enough to trigger that the first streams get re-enabled
4. VOD content that doesn't change while we sit in the loop
5. enough streams to avoid exhausting them during the cycle

Only `TIMEOUT` errors can trigger this bug AFAICT, so we should exclude those from the logic to disable streams.  Note also that live streaming already retries indefinitely by default, and that normal ABR logic will change streams for us if we timeout due to a lack of bandwidth.

Disabling streams on `TIMEOUT` was suggested initially in #4764, but was not a requirement of the OP.  It was added out of caution in #4769, but not really vetted.  Because it was not ever explicitly needed, excluding it is not a regression.

Closes #7368

### CODE REVIEW

**Review by theodab — APPROVED** [review]

**Review by avelad — COMMENTED** [review]
For me this is not valid, we should also accept errors of the TIMEOUT or BAD_HTTP_STATUS type, for Low Latency these errors are common and we should treat them as well.

**Comment by joeyparrish** [comment]
> For me this is not valid, we should also accept errors of the TIMEOUT or BAD_HTTP_STATUS type, for Low Latency these errors are common and we should treat them as well.

The TIMEOUT error is what triggers the loading loop described in #7368.

**Comment by joeyparrish** [comment]
See my latest comments in the issue.

**Review by JulianDomingo — APPROVED** [review]
I don't have any objections with this approach; I agree `TIMEOUT` events caused by transient network events do not make the stream inherently broken (plus Joey finding out `TIMEOUT` errors were initially added as a cautionary measure).

**Pull request merged**
