### PR TITLE
fix(DASH): Fix MPD Patch when SegmentTemplate is shared between Representations

### LINKED ISSUE #7214: MPD Patch: Incorrectly apply patch multiple times?
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
No

**What version of Shaka Player are you using?**
Nightly

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
No

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Chrome&Safari @ MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Nightly build on https://nightly-dot-shaka-player-demo.appspot.com/demo/

**What did you do?**
Play a Live with MPD patch

**What did you expect to happen?**
patch being applied multiple times internal

**What actually happened?**
Consider this patch
```
<Patch mpdId="res" originalPublishTime="...">
    <add sel="/MPD/Period[@id='x']/AdaptationSet[1]/SegmentTemplate/SegmentTimeline">
        <S d="1" t="3" />
    </add>
</Patch>
```
For this MPD:
```
  <Period id="x">
    <BaseURL>http://example.com</BaseURL>
    <AdaptationSet id="y" mimeType="video/mp4">
      <SegmentTemplate media="s$Number$.mp4">
        <SegmentTimeline>
            <S d="1" t="0" />
            <S d="2" t="1" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="a" bandwidth="100" ></Representation>
      <Representation id="b" bandwidth="200" ></Representation>
      <Representation id="c" bandwidth="300" ></Representation>
    </AdaptationSet>
  </Period>
```

Should result
```
        <S d="1" t="0" />
        <S d="2" t="1" />
        <S d="1" t="3" />
```

But after applying the patch,`stream.segmentIndex.indexes_[0].templateInfo_.timeline` become:
```
[
  {"start":0,"end":1,"unscaledStart":0,"partialSegments":0,"segmentPosition":1},
  {"start":1,"end":3,"unscaledStart":1,"partialSegments":0,"segmentPosition":2},
  {"start":3,"end":3,"unscaledStart":3,"partialSegments":0,"segmentPosition":3}, // 1st
  {"start":3,"end":3,"unscaledStart":3,"partialSegments":0,"segmentPosition":4}, // 2nd
  {"start":3,"end":4,"unscaledStart":3,"partialSegments":0,"segmentPosition":5} // 3rd
]
```

If I add another Representation into the AdaptationSet, the `stream.segmentIndex.indexes_[0].templateInfo_.timeline` become:
```
[
  {"start":0,"end":1,"unscaledStart":0,"partialSegments":0,"segmentPosition":1},
  {"start":1,"end":3,"unscaledStart":1,"partialSegments":0,"segmentPosition":2},
  {"start":3,"end":3,"unscaledStart":3,"partialSegments":0,"segmentPosition":3}, // 1st
  {"start":3,"end":3,"unscaledStart":3,"partialSegments":0,"segmentPosition":4}, // 2nd
  {"start":3,"end":3,"unscaledStart":3,"partialSegments":0,"segmentPosition":5} // 3rd
  {"start":3,"end":4,"unscaledStart":3,"partialSegments":0,"segmentPosition":6} // 4th
]
```

Seems this is an representation handling issue, causing patch being applied N times when there're N representations in AdaptSet.
**Are you planning send a PR to fix it?**

### PR DESCRIPTION
**Pull request by tykus160**
Fixes #7214

### CODE REVIEW

**Review by avelad — APPROVED** [review]

**Comment by avelad** [comment]
After talking to @tykus160 , it still can't be merged because there is an error in the compiled build.

**Comment by wilsonluniz-harmonicinc** [comment]
Just curious if I can get a live version of this PR for test? So that I don't need to setup my HTTPS server.

**Comment by wilsonluniz-harmonicinc** [comment]
@tykus160 Seems only `<add/>` works. I tested neither `<remove/>` or `<replace/>` works.

In practice, MPD:
```
<S d="1" t="0" />
<S d="2" t="1" />
<S d="1" t="3" />
```

Remove patch:
```
<remove sel="/MPD/Period[@id='1']/AdaptationSet[1]/SegmentTemplate/SegmentTimeline/S[t='3']">
</remove>
```

Replace patch:
```
 <replace sel="/MPD/Period[@id='1']/AdaptationSet[1]/SegmentTemplate/SegmentTimeline/S[t='3']/@r">
    3
</replace>
```

Error message:
```
Expected _class2({ startTime: 3, endTime: 4, trueEndTime: 4, ... }) to equal _class2({ startTime: 3, endTime: 6, trueEndTime: 6, ... }).
```

**Comment by avelad** [comment]
> @tykus160 Oh yes you're right. Both `<replace>` and `<remove>` not works even I put `<SegmentTemplate>` into `<Representation>` and change `@sel` respectively. Should I open another issue for that?

Yes please!

**Comment by tykus160** [comment]
@wilsonluniz-harmonicinc you can, it will make tracking of that easier.

**Review by avelad — APPROVED** [review]

**Pull request merged**
