### PR TITLE
fix(UI): Console error on remote.cancelwatchavailability() method in remote playback feature

### PR DESCRIPTION
**Pull request by Ravi-79**
This Pull request includes the fix for getting console error on remote.cancelwatchavailability() method in remote playback feature.

Fixes: https://github.com/shaka-project/shaka-player/issues/5766

### CODE REVIEW

**Comment by avelad** [comment]
@Ravi-79 can you sign the CLA? Thanks!

**Comment by Ravi-79** [comment]
> @Ravi-79 can you sign the CLA? Thanks!

Hi @avelad , Submitted CLA by my company. Waiting for Agreement to be completed.

**Comment by avelad** [comment]
The CLA is not yet valid according to the bot.

**Comment by Ravi-79** [comment]
> The CLA is not yet valid according to the bot.

Hi @avelad. the CLA was rejected due to some invalid data. Could you please abandon this PR and made the changes by yourself for this time. From next time onwards I'll create a PR after the CLA registration.

Thanks

**Comment by avelad** [comment]
@Ravi-79 I created: https://github.com/shaka-project/shaka-player/pull/5793

Thanks!

**Pull request closed without merging**
