### PR TITLE
feat(UI): Add config for refreshTickInSeconds

### PR DESCRIPTION
**Pull request by MarianoFacundoArch**
Closes https://github.com/shaka-project/shaka-player/issues/6376

### CODE REVIEW

**Comment by avelad** [comment]
@MarianoFacundoArch Please add your name and email to https://github.com/shaka-project/shaka-player/blob/main/AUTHORS and https://github.com/shaka-project/shaka-player/blob/main/CONTRIBUTORS. Thanks!

**Comment by MarianoFacundoArch** [comment]
Hi! Thanks! It is done in two commits; please let me know when it is merged. I am willing to continue collaborating! :D 
https://github.com/shaka-project/shaka-player/pull/6391
https://github.com/shaka-project/shaka-player/pull/6392

**Comment by MarianoFacundoArch** [comment]
@avelad Name added to this PR as requested; how do we proceed and get it merged?
Thanks!

**Comment by avelad** [comment]
> @avelad Name added to this PR as requested; how do we proceed and get it merged? Thanks!

We need a review from @joeyparrish or @theodab before merge it. Thanks!

**Comment by MarianoFacundoArch** [comment]
When shall this be released? In which version?

**Comment by joeyparrish** [comment]
If we don't do a new branch for v4.8, this would be out in v5.0, which we will be more cautious about.  There are other things we want to break this year, like moving to TypeScript, so it's possible that v5.0 will be delayed for a while.  If we create a v4.8.x branch without the breaking changes in it, your change would be in that branch and would be out sooner.

**Comment by joeyparrish** [comment]
We will be releasing v4.8.0 soon.

**Comment by MarianoFacundoArch** [comment]
Got it. Thank you @joeyparrish !

**Pull request merged**
