### PR TITLE
Requesting as HEAD causes response.body to be empty

### PR DESCRIPTION
**Pull request by henriquebremenkanp**
Fix for: https://github.com/shaka-project/shaka-player/issues/5164

This is my first commit to shaka-player. 
Please feel free to modify it if there's a better solution.

### CODE REVIEW

**Comment by avelad** [comment]
I don't agree with the change, @joeyparrish / @theodab , can you review it?

**Comment by LightTreason** [comment]
The specific path I see this take is we have this getMimeType call which specifies the HEAD method. This goes through netEngine.request and it eventually reaches the shaka.net.HttpFetchPlugin's parse method. This calls shaka.net.HttpFetchPlugin.request_ which has a call to clone the response, access the body, and calls getReader().

Since `body` is null after the Chromium change (https://crbug.com/1297060), it throws an uncaught exception.

If this isn't the right fix, then a better one might be to update shaka.net.HttpFetchPlugin to look at `init.method` and, if it's HEAD, skip the path that attempts to read the body.

**Comment by erik-anderson** [comment]
The specific path I see this take is we have this getMimeType call which specifies the HEAD method. This goes through netEngine.request and it eventually reaches the shaka.net.HttpFetchPlugin's parse method. This calls shaka.net.HttpFetchPlugin.request_ which has a call to clone the response, access the body, and calls getReader().

Since `body` is null after the Chromium change (https://crbug.com/1297060), it throws an uncaught exception.

If this isn't the right fix, then a better one might be to update shaka.net.HttpFetchPlugin to look at `init.method` and, if it's HEAD, skip the path that attempts to read the body.

**Comment by theodab** [comment]
I agree that I don't think this is the right change. We would be better off modifying the fetch plugin to not load the body if the method is HEAD, since we don't need the body for HEAD requests.

**Comment by joeyparrish** [comment]
Thank you for your contribution, @henriquebremenkanp, but I agree that this is not the fix we want.  It's not the same to make a full `GET` request when we are only probing for the MIME type.  This would be wasting bandwidth, and doesn't address the root of the issue.

**Pull request closed without merging**
