### PR TITLE
fix: Fix green screen issue on Edge with mixed content

### PR DESCRIPTION
**Pull request by tykus160**
On Edge, to properly play mixed content, we need to insert init segment twice for clear part - once as encrypted, and immediately again as clear. Otherwise we may encounter green screen and errors from video decoder.

### CODE REVIEW

**Comment by joeyparrish** [comment]
> On Edge, to properly play mixed content, we need to insert init segment twice for clear part - once as encrypted, and immediately again as clear. Otherwise we may encounter green screen and errors from video decoder.

The latest Edge (for several years) is based on Chromium, so this shouldn't be an issue on desktops.  Is there a particular platform that has a legacy version of Edge that has this problem?  This is the case on our Xbox, for example.

**Comment by tykus160** [comment]
@joeyparrish unfortunately is is the issue even on current Edge Chromium when using PlayReady.

**Comment by avelad** [comment]
> @joeyparrish unfortunately is is the issue even on current Edge Chromium when using PlayReady.

If Widevine is used, it doesn't happen?

**Comment by tykus160** [comment]
@avelad yes, it seems we don't need this workaround when Widevine is used.

**Comment by avelad** [comment]
> @avelad yes, it seems we don't need this workaround when Widevine is used.

So, this should be taken into account in the code, because right now it applies to ClearKey, PlayReady and Widevine.

**Comment by avelad** [comment]
@joeyparrish can review it again? Thanks!

**Review by joeyparrish — APPROVED** [review]

**Pull request merged**
