### PR TITLE
Accessibility Feature: Configurable Keyboard shortcut: toggleFullscreenOnfPress: V2

### PR DESCRIPTION
**Pull request by Ketan2010**
Description

for better accessibility keyboard shortcuts need to be added. This PR gives implementation of keyboard shortcut (f) which toggles fullscreen view of video. Which can be configured as existing UIConfigurations as follow.
Defaults to `false`

```
const config = {
    toggleFullscreenOnfPress: true,
 };
```
Such more shortcuts can be implemented for other frequent controls like Picture in Picture, Mute and Unmute, Captions etc.

Fixes # (partially)
#3223 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by surajkumar-sk** [comment]
@Ketan2010 you added `this.pressedKeys_.delete(event.key);` on line 1274, you are not adding event to pressed keys so you don't need to delete it, please remove the line, it might cause unnecessary bugs if the user types shift+f by mistake or just for fun.

**Comment by surajkumar-sk** [comment]
@Ketan2010 and also I don't think you would need lines 1267 and 1269 also , because you are listening to keyboard event on window and it doesn't matter if any container element is active , you could directly call `mousemove()` function to display the control panel elements.

**Comment by surajkumar-sk** [comment]
@Ketan2010 i am sorry for posting with long breaks, did you test the working of your code , that is when f is pressed it goes to full screen and video controls and seek bar shows up .

**Comment by Ketan2010** [comment]
@surajkumar-sk,
 Yes, I checked with that before commit. and it works fine.

Thanks you for all suggestions!

**Comment by avelad** [comment]
@Ketan2010  I see that there are conflicts to be able to merge, can you rebase?

**Comment by avelad** [comment]
Closing due to inactivity.

**Pull request closed without merging**
