### PR TITLE
test: End-to-end WebVTT layout tests

### PR DESCRIPTION
**Pull request by joeyparrish**
Many of these are rendered incorrectly in some way.

Related to work on PR #4767

### CODE REVIEW

**Comment by theodab** [comment]
Wow, you weren't wrong, we really are failing a lot of webVTT tests, huh.

**Review by theodab — DISMISSED** [review]

**Review by avelad — CHANGES_REQUESTED** [review]
I think that https://github.com/shaka-project/shaka-player/pull/4922 and https://github.com/shaka-project/shaka-player/pull/4920 fixes several issues. Please, review it before merge this PR.

**Comment by joeyparrish** [comment]
@avelad, I hear you.  I'll work on that Monday.

**Comment by avelad** [comment]
@joeyparrish can you rebase and resolve the conflicts? Thanks!

**Comment by joeyparrish** [comment]
I'm going to:

1. Merge and rebase everything
1. Review screenshots again locally
1. Force-push this PR with updated screenshots
1. Run the lab tests again to confirm everything
1. Close this PR
1. Open two new PRs, one with the tests only, and one with the images only, for ease of review

Thanks, everyone, for their patience!

**Pull request closed without merging**
