### PR TITLE
fix: Forbid usage of instanceof ArrayBuffer

### LINKED ISSUE #6279: Encrypted media playback freezes on documentPip if pssh is obtained from the media
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Can't due to requiring a custom manifest parser OR a specific media asset 

**What browser and OS are you using?**
Chrome latest

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Provided that:
  - A sample media is encrypted using Widevine
  - A sample media asset is provided with no pssh data for widevine OR shaka Player is using a custom manifest parser that does not read said widevine's pssh data from the manifest even if available.
  - Therefore, shaka Player is forced to react to `encrypted` events from the player that surface the initData in ArrayBuffer form, and process them.

One can reproduce a bug doing the following:
1. Load a site with:
   - A video element inside a `container div`.
   - A button to enable documentPip and move the `container div` to the documentPip window.
   - A button to load a particular media asset into the video element using shaka player and starts playing it.
2. Click button to launch a documentPip window.
3. Click button to load media.

**What did you expect to happen?**

- Media is loaded on the documentPip and plays without issues.

**What actually happened?**

- Media shows first frame and freezes (or if any initial segments are unencrypted, it will play those and then freeze). By freeze I mean the player will not report any failures but rendering is stopped.

The bug is caused by this line: https://github.com/shaka-project/shaka-player/blob/bb712c02835f1214be5f23c7f37891eb206ee8e1/lib/util/buffer_utils.js#L65 

Using `instanceof ArrayBuffer` on the initData obtained from the player's `encrypted` event *while on documentPip* will actually return false, I presume due to the fact that the ArrayBuffer instance is different if coming from the documentPip context, and is being compared with the one from the main window.

Removing that check and building shaka fixed the issue.

Sorry for not providing a sample atm but I can't easily share the custom parser or media required, and can't set up a codepen with documentPip since it won't work on iframes.

### PR DESCRIPTION
**Pull request by tykus160**
Fixes #6279

### CODE REVIEW

**Comment by tykus160** [comment]
@shaka-bot test

**Comment by tykus160** [comment]
Lab tests are needed before merge to ensure `ArrayBuffer.isView()` is available on older platforms.

**Comment by avelad** [comment]
@tykus160 I think to cover all cases of #6279 we should also remove the use of instanceof Uint8Array

**Review by theodab — APPROVED** [review]

**Review by avelad — APPROVED** [review]

**Review by theodab — APPROVED** [review]

**Comment by avelad** [comment]
@shaka-bot test

**Pull request merged**
