### PR TITLE
fix: exclude "future" segments from presentation timeline auto correct drift calculations

### LINKED ISSUE #4944: autoCorrectDrift is incorrectly calculated for certain live streams
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.4.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, Safari, Edge on macOS Monterey, Tizen, WebOS and others.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not device specific

**What are the manifest and license server URIs?**

Available upon request

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

When playing a simulated live stream<sup>*</sup>, the auto correct drift functionality uses segments ahead of the live edge in its calculations. This is because the current content period is published and available, but the live edge is somewhere in the middle of the period. Using the period's segment template the auto correct calculation uses segments that are "in the future" which results in a negative `presentationStartTime`. This then incorrectly moves the calculated live edge to the end of the period. The issue does not occur when `manifest.dash.autoCorrectDrift` is set to `false`.

<sup>*</sup>A live stream created by stitching together VOD assets and ad periods. 

**What did you expect to happen?**
The live edge should be the same regardless of the `manifest.dash.autoCorrectDrift`'s value.

**What actually happened?**

The live edge is calculated "in the future", resulting in stalled playback.

### PR DESCRIPTION
**Pull request by littlespex**
Resolves #4944

### CODE REVIEW

**Review by avelad — APPROVED** [review]

**Review by avelad — CHANGES_REQUESTED** [review]
There are some errors in the tests. Can you review it?

**Review by theodab — APPROVED** [review]
LGTM, following test fixes.

**Comment by littlespex** [comment]
@joeyparrish All of these tests fail is the test parser is configured with `autoCorrectDrift` set to `false`. Are the tests valid? Shouldn't they produce the same results regardless of that setting?

**Comment by joeyparrish** [comment]
I don't know off-hand.  I did not write that feature, and my understanding of it is weak.

**Comment by avelad** [comment]
@littlespex Have you found any solution?

**Comment by littlespex** [comment]
Unfortunately no. Regardless of this fix, all of the failing tests would also need to pass when the player is configured with `autoCorrectDrift: false`, and they currently don't. We are still investigating possible solutions, but any input would be greatly appreciated.

**Comment by littlespex** [comment]
Updating the unit test to use a realistic date value solved the problem. This is ready for review now.

**Review by avelad — APPROVED** [review]

**Review by theodab — APPROVED** [review]

**Review by joeyparrish — APPROVED** [review]

**Pull request merged**
