### PR TITLE
feat: export period combiner

### PR DESCRIPTION
**Pull request by baconz**
See #5307

### CODE REVIEW

**Comment by joeyparrish** [comment]
@baconz, long time, no see!  Thanks for the PR.  Looks good to me.

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
JFYI, it has been proposed to trash this class in v5 and go back to modeling periods explicitly in the manifest structure.  We haven't committed to it, but it is a breaking change we're considering in the next ~12 months.

**Comment by baconz** [comment]
Thanks for getting this out so quickly!

Interesting about going back to the old manifest format. What is the reasoning for switching back?

**Comment by joeyparrish** [comment]
Primarily that period combiner is complicated and uses more memory than other approaches might.

**Pull request merged**
